baseurl = "https://tsuro624.github.io/noraneko-monomane-grand-prix-ai-no-uta/"
languageCode = "ja"
title = "野良猫ものまねグランプリ 愛の歌が溢れ出てきて止まらねえんだよ!|つうろ"
theme = "vanilla-bootstrap-hugo-theme"
canonifyurls = true



[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"
#
# [menu]
#   [[menu.main]]
#     name = "Home"
#     pre = "home"
#     url = "/"
#     weight = 1


[params]
  includeBootstrapJs = false
  showActiveNav = false
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = ""
  hideFooter = true
