baseurl = "https://tsuro624.github.io/noraneko-monomane-grand-prix-ai-no-uta/"
languageCode = "ja"
title = "愛の歌が溢れ出てきて止まらねえんだよ!のものまね"
theme = "vanilla-bootstrap-hugo-theme"
canonifyurls = true



[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"


[params]
  includeBootstrapJs = false
  showActiveNav = false
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Welcome to the Vanilla theme demo. Have a look around. Maybe even eat some ice cream."
  footerText = ""
  hideFooter = true
